---
title: "Mock-Assignment"
author: "Sam Straus"
date: "05/08/2022"
output: html_document
---

```{r setup, include=FALSE}

library("renv")
library("palmerpenguins")
library("tidyverse")
library(ggplot2)
library(cowplot)

#renv::init()
```

```{r, echo=TRUE}

dat <- read.csv("data/TLW_invertebrateDensity.csv")

table(dat$catchment)

## catchments 31, 33, and 34 were the ones that experienced forest harvest, create new column
dat <- dat %>% mutate(harvest = if_else(catchment == "33" | catchment == "34L" | catchment == "34M" | 
                                   catchment == "34U", true = "yes", false = "no"))

table(dat$harvest)

# for the purposes of this mock assignment, let's just stick on with one genus: Baetis (a genus of mayfly, the order of which are stream quality indicators 
head(dat)
baetis <- dat %>% select(catchment, year, month, replicate, Baetis, harvest)

baetis.sum <- baetis %>% group_by(catchment, year, month, harvest) %>% summarize(mean.dens = mean(Baetis))


## need date format to plot as a time series
table(baetis.sum$month)
baetis.sum <- baetis.sum %>% mutate(month2 = if_else(month == "june", "06", if_else(month == "may", "05", 
                      if_else(month == "november", "11", if_else(month =="october", "10",
                      if_else(month == "september", "09", "0"))))))

# unite month and year
baetis.sum <- baetis.sum %>% unite(col = "year.month", year, month2, sep = "-")

## adding a day to get into yyyy-mm-dd format that R likes, the data file does not specify the day, so we're just going to use the first of the month

baetis.sum <- baetis.sum %>% mutate(ymd = as.Date(paste(year.month,"-01",sep="")))

## double check that are actually in a date format
str(baetis.sum$ymd) # nice!

p <- ggplot(baetis.sum, aes(x=ymd, y=mean.dens, color = harvest)) +
  geom_line() + 
  xlab("Year")+
  ylab("Mean density (# per sq. m)")+
  theme_cowplot()
  
p

```





